<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>

	<key>scopeName</key>
	<string>source.prototxt</string>
	
	<key>fileTypes</key>
	<array>
		<string>prototxt</string>
	</array>

	<key>foldingStartMarker</key>
	<string>\{\s*$</string>

	<key>foldingStopMarker</key>
	<string>^\s*\}</string>	

	<key>name</key>
	<string>prototxt</string>

	<key>patterns</key>
	<array>

		<dict>
			<key>name</key>
			<string>keyword.other.prototxt</string>
			<key>match</key>
			<string>\b(layer)\b</string>					
		</dict>

		<dict>
			<key>name</key>
			<string>comment.line.number-sign.prototxt</string>
			<key>match</key>
			<string>#.*$\n?</string>	
		</dict>

		<dict>
			<key>name</key>
			<string>constant.numeric.prototxt</string>
			<key>match</key>
			<string>\b([-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?)\b</string>
		</dict>

		<dict>
			<key>name</key>
			<string>string.quoted.double.prototxt</string>
			<key>begin</key>
			<string>"</string>			
			<key>end</key>
			<string>"</string>
			<key>patterns</key>
			<array>				
				<dict>
					<key>name</key>
					<string>constant.character.escape.prototxt</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		
	</array>

</dict>
</plist>